services:
  backend:
    build: ./backend
    container_name: starwars-backend
    ports:
      - "6969:8000"
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    container_name: starwars-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE=http://backend:8000
    depends_on:
      - backend 