import os
import logging
from fastapi import APIRouter, Query, Body
from typing import Optional
from fastapi.responses import JSONResponse
from . import swapi_client, utils, models
from dotenv import load_dotenv
import asyncio

load_dotenv()

router = APIRouter()

PAGE_SIZE = 15

# Set up logging
logging.basicConfig(level=os.getenv("LOG_LEVEL", "INFO"))
logger = logging.getLogger("starwars-app")

@router.get("/people", response_model=models.PaginatedResponse)
async def get_people(
    page: int = Query(1, ge=1),
    search: Optional[str] = None,
    sort_by: Optional[str] = Query("name"),
    order: Optional[str] = Query("asc")
):
    logger.info(f"[PEOPLE] page={page} search={search} sort_by={sort_by} order={order}")
    data = await swapi_client.fetch_people(page)
    items = data.get("results", [])
    # Filter by name
    items = utils.filter_by_name(items, search)
    # Sort
    sorters = {
        "name": lambda x: x.get("name", ""),
        "created": lambda x: x.get("created", "")
    }
    items = utils.sort_items(items, sort_by, order, sorters)
    # Manual pagination
    paginated = utils.paginate(items, 1, PAGE_SIZE)  # Always page 1 because SWAPI already paginated
    return models.PaginatedResponse(
        count=len(items),
        next=data.get("next"),
        previous=data.get("previous"),
        results=paginated
    )

@router.get("/planets", response_model=models.PaginatedResponse)
async def get_planets(
    page: int = Query(1, ge=1),
    search: Optional[str] = None,
    sort_by: Optional[str] = Query("name"),
    order: Optional[str] = Query("asc")
):
    logger.info(f"[PLANETS] page={page} search={search} sort_by={sort_by} order={order}")
    data = await swapi_client.fetch_planets(page)
    items = data.get("results", [])
    # Filter by name
    items = utils.filter_by_name(items, search)
    # Sort
    sorters = {
        "name": lambda x: x.get("name", ""),
        "created": lambda x: x.get("created", "")
    }
    items = utils.sort_items(items, sort_by, order, sorters)
    # Manual pagination
    paginated = utils.paginate(items, 1, PAGE_SIZE)
    return models.PaginatedResponse(
        count=len(items),
        next=data.get("next"),
        previous=data.get("previous"),
        results=paginated
    )

@router.post("/simulate-ai-insight")
async def simulate_ai_insight(payload: dict = Body(...)):
    name = payload.get("name", "")
    if not name:
        return JSONResponse(status_code=400, content={"error": "Missing 'name' in request body"})
    # Fake AI output
    description = f"{name} is a legendary figure in the Star Wars universe, known for their unique adventures and impact on the galaxy. (Generated by fake AI)"
    logger.info(f"[SIMULATE-AI-INSIGHT] name={name}")
    return {"insight": description} 